# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.29

    - name: Lint
      run: golangci-lint run ./... --verbose --build-tags build
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Lint
      run: golangci-lint run ./... --verbose --build-tags build

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...
